---
name: "Evergreen action"
author: "github"
description: "A GitHub Action to request dependabot enablement on eligible repositories in an organization."
runs:
  using: "docker"
  image: "docker://ghcr.io/github-community-projects/evergreen:v2"
branding:
  icon: "file-plus"
  color: "green"
